# METADATA FOR PROJECT ------------------------------------------------------------------------------------------------
meta:
  lang:         en
  title:        New document
  description:  Easy frontend
  author:       romanVia

# IMAGES SETTINGS -----------------------------------------------------------------------------------------------------
image:
  favicon:      img/favicon.png
  imageSrc:     #img/...
  inlineSvg:    true

# VENDOR PREFIX AUTO ADDING SETTINGS ----------------------------------------------------------------------------------
autoprefixer:
  browsers:     [last 2 versions, ie 8, ie 9]
  cascade:      false

# BUILT FILES MINIMIZATION --------------------------------------------------------------------------------------------
min:
  html:         false
  svg:          true
  css:          false
  js:           true
  image:        true

# SERVER STARTING AND BROWSER SYNCHRONIZATION -------------------------------------------------------------------------
browserSync:
  server:
    baseDir:    'build/'
#    index:      pablic.html
#    directory:  true
#  tunnel:       true
#  host:         myhost
#  port:         9000
  logPrefix:    BROWSER

# CDN REFERENCES FOR STYLES -------------------------------------------------------------------------------------------
stylesCDNs:
  - //fonts.googleapis.com/css?family=Roboto:400,300
  # https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css
  # https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.min.css

# CDN REFERENCES FOR SCRIPTS ------------------------------------------------------------------------------------------
scriptsCDNs:
  # https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js
  # https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js

# MAIN FILES FOR PARSING ----------------------------------------------------------------------------------------------
mainFiles:
  markup:       index.twig
  style:        style.scss
  script:       main.js

# DESTINATION FOLDERS FOR BUILT FILES ---------------------------------------------------------------------------------
dest:
  public:       'public'
  build:        'build'
  markup:       'build'
  style:        'build'
  script:       'build'
  image:        'build/img'
  inlineSvg:    'build/imgi'

# FOLDERS OF SOURCE FILES FOR BUILDING --------------------------------------------------------------------------------
src:
  markup:       'src/markup/**/*.twig'
  style:        'src/styles/**/*.scss'
  script:       'src/scripts/**/*.js'
  image:        ['src/images/**/*.*', '!src/images/inline/**']
  inlineSvg:    'src/images/inline/**/*.svg'
